// <auto-generated />
namespace Contoso.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class datetime2_instructor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetime2_instructor));
        
        string IMigrationMetadata.Id
        {
            get { return "201806042202032_datetime2_instructor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
